spring:
  data:
    mongodb:
      database: library
      #port: 27017
      #host: localhost
  mongodb:
    embedded:
      version: 3.5.5
  main:
    allow-circular-references: true

logging:
  level:
    ROOT: INFO
