DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS BOOK_GENRE;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS COMMENT;

CREATE TABLE AUTHOR
(
    ID   bigserial PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK
(
    ID   bigserial PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE GENRE
(
    ID   bigserial PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK_GENRE
(
    BOOK_ID  BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    CONSTRAINT `BOOK_GENRE_BOOK_ID_FK`
        FOREIGN KEY (`BOOK_ID`)
            REFERENCES `BOOK` (`ID`),
    CONSTRAINT `BOOK_GENRE_GENRE_ID_FK`
        FOREIGN KEY (`GENRE_ID`)
            REFERENCES `GENRE` (`ID`)
);

CREATE TABLE AUTHOR_BOOK
(
    AUTHOR_ID BIGINT NOT NULL,
    BOOK_ID   BIGINT NOT NULL,
    CONSTRAINT `AUTHOR_BOOK_AUTHOR_ID_FK`
        FOREIGN KEY (`AUTHOR_ID`)
            REFERENCES `AUTHOR` (`ID`),
    CONSTRAINT `AUTHOR_BOOK_BOOK_ID_FK`
        FOREIGN KEY (`BOOK_ID`)
            REFERENCES `BOOK` (`ID`)
);

CREATE TABLE COMMENT
(
    ID      bigserial PRIMARY KEY NOT NULL,
    BOOK_ID BIGINT references BOOK (ID),
    MESSAGE VARCHAR(255)
);


/*alter table BOOK_GENRE
    add foreign key (BOOK_ID) references BOOK;

alter table BOOK_GENRE
    add foreign key (GENRE_ID) references GENRE;
*/